mkdir .streamlit
echo "[server]" > .streamlit/config.toml

[server]
enableCORS = false
headless = true

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"

[browser]
gatherUsageStats = false

hide_streamlit_style = """
    <style>
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    </style>
"""
st.markdown(hide_streamlit_style, unsafe_allow_html=True)
