[theme]
base = "light"  # Default theme (use "dark" for dark mode)
primaryColor = "#1E90FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[ui]
hideThemeSwitch = true  # Show the dark/light mode toggle
hideStreamlitMark = true # Hide Streamlit watermark

[server]
headless = true

[browser]
gatherUsageStats = false

[global]
disableWatchdogWarning = true
